version: "2"
services:
   influxdb:
      image: influxdb:1.8
      container_name: influxdb
      restart: unless-stopped
      volumes:
         - ${PWD}/influxdb/data:/var/lib/influxdb
         - ${PWD}/influxdb/ssl:/etc/influxdb/ssl
         - ${PWD}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      ports:
         - 8086:8086
      environment:
         - INFLUXDB_TLS_CIPHERS=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256
         - INFLUXDB_TLS_MIN_VERSION=tls1.2
         - INFLUXDB_TLS_MAX_VERSION=tls1.3
         - INFLUXDB_HTTP_HTTPS_ENABLED=true
         - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/influxdb/ssl/influxdb.pem
         - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/influxdb/ssl/influxdb.key

      command: -config /etc/influxdb/influxdb.conf

   grafana:
     image: grafana/grafana:6.7.3
     container_name: grafana
     restart: unless-stopped
     volumes:
        - ${PWD}/grafana/data:/var/lib/grafana
     ports:
        - 3000:3000
     depends_on:
        - influxdb
